In [81]:
pip install plotly==4.1.0

In [1]:
import plotly.graph_objects as go
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Wine.csv')

In [3]:
df.shape

(178, 14)

In [4]:
df.columns

Index(['Alcohol', 'Malic_Acid', 'Ash', 'Ash_Alcanity', 'Magnesium',
       'Total_Phenols', 'Flavanoids', 'Nonflavanoid_Phenols',
       'Proanthocyanins', 'Color_Intensity', 'Hue', 'OD280', 'Proline',
       'Customer_Segment'],
      dtype='object')

In [5]:
labels_df = df['Customer_Segment']
df = df.drop(columns = 'Customer_Segment')
df.head()

Alcohol  Malic_Acid   Ash  ...   Hue  OD280  Proline
0    14.23        1.71  2.43  ...  1.04   3.92     1065
1    13.20        1.78  2.14  ...  1.05   3.40     1050
2    13.16        2.36  2.67  ...  1.03   3.17     1185
3    14.37        1.95  2.50  ...  0.86   3.45     1480
4    13.24        2.59  2.87  ...  1.04   2.93      735

[5 rows x 13 columns]

In [6]:
df = df.rename(columns={"Alcohol": "Alcool", "Ash": "Po", "Ash_Alcanity": "Ancalinidade_po", "Magnesium": "Magensio", "Color_Intensity": "Intensidade_cor"})
df.head()

Alcool  Malic_Acid    Po  ...   Hue  OD280  Proline
0   14.23        1.71  2.43  ...  1.04   3.92     1065
1   13.20        1.78  2.14  ...  1.05   3.40     1050
2   13.16        2.36  2.67  ...  1.03   3.17     1185
3   14.37        1.95  2.50  ...  0.86   3.45     1480
4   13.24        2.59  2.87  ...  1.04   2.93      735

[5 rows x 13 columns]

In [7]:
colunas = df.columns
colunas

Index(['Alcool', 'Malic_Acid', 'Po', 'Ancalinidade_po', 'Magensio',
       'Total_Phenols', 'Flavanoids', 'Nonflavanoid_Phenols',
       'Proanthocyanins', 'Intensidade_cor', 'Hue', 'OD280', 'Proline'],
      dtype='object')

In [89]:
df.describe()

Alcool  Malic_Acid          Po  ...         Hue       OD280      Proline
count  178.000000  178.000000  178.000000  ...  178.000000  178.000000   178.000000
mean    13.000618    2.336348    2.366517  ...    0.957449    2.611685   746.893258
std      0.811827    1.117146    0.274344  ...    0.228572    0.709990   314.907474
min     11.030000    0.740000    1.360000  ...    0.480000    1.270000   278.000000
25%     12.362500    1.602500    2.210000  ...    0.782500    1.937500   500.500000
50%     13.050000    1.865000    2.360000  ...    0.965000    2.780000   673.500000
75%     13.677500    3.082500    2.557500  ...    1.120000    3.170000   985.000000
max     14.830000    5.800000    3.230000  ...    1.710000    4.000000  1680.000000

[8 rows x 13 columns]

In [90]:
matriz_corr = df.corr()

In [91]:
matriz_corr

Alcool  Malic_Acid  ...     OD280   Proline
Alcool                1.000000    0.094397  ...  0.072343  0.643720
Malic_Acid            0.094397    1.000000  ... -0.368710 -0.192011
Po                    0.211545    0.164045  ...  0.003911  0.223626
Ancalinidade_po      -0.310235    0.288500  ... -0.276769 -0.440597
Magensio              0.270798   -0.054575  ...  0.066004  0.393351
Total_Phenols         0.289101   -0.335167  ...  0.699949  0.498115
Flavanoids            0.236815   -0.411007  ...  0.787194  0.494193
Nonflavanoid_Phenols -0.155929    0.292977  ... -0.503270 -0.311385
Proanthocyanins       0.136698   -0.220746  ...  0.519067  0.330417
Intensidade_cor       0.546364    0.248985  ... -0.428815  0.316100
Hue                  -0.071747   -0.561296  ...  0.565468  0.236183
OD280                 0.072343   -0.368710  ...  1.000000  0.312761
Proline               0.643720   -0.192011  ...  0.312761  1.000000

[13 rows x 13 columns]

In [92]:
pip install biokit

In [8]:
from biokit.viz import corrplot
import matplotlib.pyplot as plt

In [9]:
corr_graph = corrplot.Corrplot(matriz_corr)
corr_graph.plot(upper='ellipse', fontsize="x-large")
fig = plt.gcf()
fig.set_size_inches(13, 8)
fig.show()

NameError: ignored

In [10]:
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
np_df = min_max_scaler.fit_transform(df)

In [11]:
df = pd.DataFrame(np_df, columns = colunas)

In [12]:
df.describe()

Alcool  Malic_Acid          Po  ...         Hue       OD280     Proline
count  178.000000  178.000000  178.000000  ...  178.000000  178.000000  178.000000
mean     0.518584    0.315484    0.538244  ...    0.388170    0.491460    0.334446
std      0.213639    0.220780    0.146708  ...    0.185831    0.260070    0.224613
min      0.000000    0.000000    0.000000  ...    0.000000    0.000000    0.000000
25%      0.350658    0.170455    0.454545  ...    0.245935    0.244505    0.158702
50%      0.531579    0.222332    0.534759  ...    0.394309    0.553114    0.282097
75%      0.696711    0.462945    0.640374  ...    0.520325    0.695971    0.504280
max      1.000000    1.000000    1.000000  ...    1.000000    1.000000    1.000000

[8 rows x 13 columns]

In [13]:
np_df = min_max_scaler.inverse_transform(df)

In [14]:
df_nao_normalizado = pd.DataFrame(np_df, columns = colunas)
df_nao_normalizado.describe()

Alcool  Malic_Acid          Po  ...         Hue       OD280      Proline
count  178.000000  178.000000  178.000000  ...  178.000000  178.000000   178.000000
mean    13.000618    2.336348    2.366517  ...    0.957449    2.611685   746.893258
std      0.811827    1.117146    0.274344  ...    0.228572    0.709990   314.907474
min     11.030000    0.740000    1.360000  ...    0.480000    1.270000   278.000000
25%     12.362500    1.602500    2.210000  ...    0.782500    1.937500   500.500000
50%     13.050000    1.865000    2.360000  ...    0.965000    2.780000   673.500000
75%     13.677500    3.082500    2.557500  ...    1.120000    3.170000   985.000000
max     14.830000    5.800000    3.230000  ...    1.710000    4.000000  1680.000000

[8 rows x 13 columns]

In [15]:
from sklearn.cluster import KMeans

In [101]:
agrupador = KMeans(n_clusters=5)

In [102]:
agrupador.fit(df)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=5, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [22]:
labels = agrupador.labels_
print(labels)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 3 1 1 3 3 1 3 1 3 1 0
 3 1 1 1 1 3 3 3 1 4 3 3 1 1 1 1 1 1 1 3 3 0 1 3 3 3 3 1 3 1 3 1 1 1 3 3 3
 3 1 1 3 1 3 3 4 3 3 3 3 3 3 3 3 1 3 4 1 4 2 4 1 4 4 4 4 4 4 4 4 4 2 4 4 4
 2 2 2 2 2 2 2 4 2 4 2 2 4 4 4 4 2 4 2 2 2 2 4 2 2 4 2 2 2 2]


In [104]:
agrupador.fit(df)
labels = agrupador.labels_
print(labels)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 3 3 3 4 3 4 4 4 3 4 3 4 4 1
 4 3 4 3 4 4 4 4 3 2 4 4 3 3 3 3 3 3 3 4 4 1 0 4 4 4 4 3 4 3 4 3 4 3 4 4 4
 4 3 3 4 3 4 4 2 4 4 4 4 4 4 4 4 3 4 3 0 0 0 0 2 2 2 2 2 2 2 2 2 2 0 2 2 2
 2 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2]


In [105]:
fig = go.Figure()
fig.add_trace(go.Scatter(x = df['Intensidade_cor'], y =df['Alcool'], mode="markers", marker=dict(color=agrupador.labels_.astype(np.float)),text=labels))
fig.show()

In [106]:
agrupador = KMeans(n_clusters=3)
agrupador.fit(df)
labels = agrupador.labels_
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 1, 1, 1, 1,
       1, 1, 2, 1, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2], dtype=int32)

In [107]:
fig = go.Figure()
fig.add_trace(go.Scatter(x = df['Intensidade_cor'], y =df['Alcool'], mode="markers", marker=dict(color=agrupador.labels_.astype(np.float)),text=labels))
fig.show()

In [108]:
fig = go.Figure()
fig.add_trace(go.Scatter3d(x = df['Intensidade_cor'], y=df['Alcool'], z=df['Proline'], mode='markers', marker=dict(color=labels.astype(np.float)), text=labels))
fig.show()

In [109]:
fig.update_layout(scene=dict(
    xaxis_title="Intensidade de cor",
    yaxis_title="Àlcool",
    zaxis_title="Proline"
))
fig.show()

In [110]:
centros = pd.DataFrame(agrupador.cluster_centers_)
centros.columns = df.columns
centros

Alcool  Malic_Acid        Po  ...       Hue     OD280   Proline
0  0.705651    0.248429  0.584904  ...  0.477809  0.690386  0.593894
1  0.313367    0.235617  0.473050  ...  0.472190  0.584220  0.156375
2  0.546686    0.484409  0.561596  ...  0.188889  0.158527  0.249115

[3 rows x 13 columns]

In [111]:
fig.add_trace(go.Scatter3d(x=  centros['Intensidade_cor'], y=centros['Alcool'], z=centros['Proline'], mode='markers', marker=dict(color='red'), text=[0,1,2]))
fig.show()

In [112]:
from sklearn.cluster import DBSCAN
agrupador =  DBSCAN(eps = 1.31, min_samples = 15, metric='manhattan')
agrupador.fit(df)

DBSCAN(algorithm='auto', eps=1.31, leaf_size=30, metric='manhattan',
       metric_params=None, min_samples=15, n_jobs=None, p=None)

In [113]:
agrupador.labels_

array([ 0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0, -1,  0, -1,  0, -1,  0, -1,  0,  0,  0,  0, -1,
        0,  0,  0,  0,  0,  0,  0,  0, -1, -1, -1, -1, -1, -1, -1, -1,  1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1,
        1, -1, -1, -1, -1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
       -1,  1,  1, -1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1,  1,  1, -1,
        1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1,  2, -1,  2, -1,  2,
       -1, -1,  2, -1, -1,  2, -1, -1,  2,  2, -1,  2,  2,  2, -1, -1, -1,
        2, -1,  2,  2, -1, -1, -1,  2,  2,  2,  2,  2, -1,  2,  2,  2, -1,
        2,  2,  2,  2,  2,  2,  2,  2])

In [114]:
np.unique(agrupador.labels_)

array([-1,  0,  1,  2])

In [115]:
agrupador = DBSCAN(eps = 0.5, min_samples= 15, metric='euclidean')
agrupador.fit(df)
agrupador.labels_

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0, -1,  0, -1,  0, -1,  0,  0,  0,  0,  0,  0, -1,
        0,  0,  0,  0,  0,  0,  0,  0, -1, -1, -1,  0,  0, -1,  0,  0,  0,
       -1, -1, -1, -1,  0, -1, -1, -1,  0,  0, -1, -1,  0,  0,  0,  1, -1,
        0,  0,  0,  0,  0,  0,  0, -1,  0,  0, -1, -1,  0, -1, -1,  0,  0,
        0,  0,  0, -1,  0,  0,  0, -1, -1,  0,  0,  0,  0, -1,  0,  0, -1,
        0,  0, -1, -1, -1, -1,  0,  0, -1,  0, -1, -1,  1,  1, -1, -1,  1,
       -1, -1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1,
        1, -1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1])

In [36]:
from sklearn.cluster import MeanShift

In [37]:
agrupador = MeanShift()
agrupador.fit(df)
agrupador.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [38]:
from sklearn.cluster import estimate_bandwidth

In [39]:
BW = estimate_bandwidth(df, quantile = 0.1)
agrupador = MeanShift(bandwidth = BW)
agrupador.fit(df)

MeanShift(bandwidth=0.5904473777050576, bin_seeding=False, cluster_all=True,
          max_iter=300, min_bin_freq=1, n_jobs=None, seeds=None)

In [120]:
agrupador.cluster_centers_

array([[0.41329887, 0.21096838, 0.486822  , 0.44504786, 0.2501941 ,
        0.50424877, 0.42148885, 0.34568733, 0.37578864, 0.18122257,
        0.46297909, 0.64508111, 0.26896525],
       [0.55708502, 0.54368096, 0.5658851 , 0.54996035, 0.30518395,
        0.22590628, 0.08249486, 0.64054185, 0.21944512, 0.51238295,
        0.17469252, 0.1722551 , 0.26359779],
       [0.34385965, 0.09749671, 0.32442068, 0.32302405, 0.86594203,
        0.38045977, 0.30801688, 0.26415094, 0.76866456, 0.14249147,
        0.55826558, 0.51282051, 0.37351403],
       [0.75789474, 0.18478261, 0.70053476, 0.67783505, 0.25543478,
        0.59310345, 0.18248945, 0.74528302, 0.65772871, 0.94667235,
        0.07317073, 0.21978022, 0.25820257],
       [0.51578947, 0.18379447, 0.6631016 , 1.        , 0.75      ,
        0.8       , 0.53797468, 0.1509434 , 0.48895899, 0.17662116,
        0.67479675, 0.81684982, 0.5042796 ],
       [0.35263158, 0.03952569, 0.        , 0.        , 0.19565217,
        0.34482759, 0.04852

In [121]:
fig = go.Figure()
fig.add_trace(go.Scatter3d(x=df['Intensidade_cor'],
                         y=df['Alcool'], z=df['Proline'],
                         mode = 'markers',                      
                          marker = dict(color = agrupador.labels_.astype(np.float)),
                        text = [0, 1, 2]))
fig.show()

In [122]:
fig.update_layout(scene = dict(
                    xaxis_title='Intensidade de Cor',
                    yaxis_title='Àlcool',
                    zaxis_title='Proline'))
fig.show()

In [123]:
centros = pd.DataFrame(agrupador.cluster_centers_)
centros.columns = colunas

In [124]:
fig.add_trace(go.Scatter3d(x=centros['Intensidade_cor'],
                         y=centros['Alcool'], z=centros['Proline'],
                         mode = 'markers',                  
                          marker = dict(color = 'red'),
                        text = [0, 1, 2]))

In [16]:
agrupador = KMeans(n_clusters=5)
agrupador.fit(df)
agrupador.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 3, 1, 1,
       3, 3, 1, 3, 1, 3, 1, 0, 3, 1, 1, 1, 1, 3, 3, 3, 1, 4, 3, 3, 1, 1,
       1, 1, 1, 1, 1, 3, 3, 0, 1, 3, 3, 3, 3, 1, 3, 1, 3, 1, 1, 1, 3, 3,
       3, 3, 1, 1, 3, 1, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 4, 1, 4,
       2, 4, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 2, 2, 2, 2, 2, 2,
       2, 4, 2, 4, 2, 2, 4, 4, 4, 4, 2, 4, 2, 2, 2, 2, 4, 2, 2, 4, 2, 2,
       2, 2], dtype=int32)

In [24]:
fig = go.Figure()
fig.add_trace(go.Scatter3d(x=df['Intensidade_cor'], y=df['Alcool'], z=df['Proline'], mode='markers', marker=dict(color= labels.astype(np.float)),
                           text=labels))
fig.show()

In [25]:
from sklearn.metrics import silhouette_score

In [27]:
faixa_n_clusters = [i for i in range(2,10)]
faixa_n_clusters

[2, 3, 4, 5, 6, 7, 8, 9]

In [29]:
valores_silhueta = []
for k in faixa_n_clusters:
  agrupador = KMeans(n_clusters=k)
  labels = agrupador.fit_predict(df)
  media_silhueta = silhouette_score(df, labels)
  valores_silhueta.append(media_silhueta)

valores_silhueta

[0.29872218159747743,
 0.3008938518500134,
 0.25993667561623146,
 0.25696691445938696,
 0.20606927972468814,
 0.19691109020603767,
 0.14797290509663089,
 0.18458074031094265]

In [31]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=faixa_n_clusters, y=valores_silhueta))
fig.update_layout(title="Valores de silhueta médios", xaxis_title="Nº de clusters", yaxis_title="Valor médio de silhueta")
fig.show()

In [51]:
faixa_quantil = np.linspace(0.02, 0.5, 30)
faixa_quantil

array([0.02      , 0.03655172, 0.05310345, 0.06965517, 0.0862069 ,
       0.10275862, 0.11931034, 0.13586207, 0.15241379, 0.16896552,
       0.18551724, 0.20206897, 0.21862069, 0.23517241, 0.25172414,
       0.26827586, 0.28482759, 0.30137931, 0.31793103, 0.33448276,
       0.35103448, 0.36758621, 0.38413793, 0.40068966, 0.41724138,
       0.4337931 , 0.45034483, 0.46689655, 0.48344828, 0.5       ])

In [52]:
valores_silhueta =  []
quantil_plot = []
for quantil in faixa_quantil:
  bw = estimate_bandwidth(df, quantile=quantil)
  agrupador = MeanShift(bw)
  labels = agrupador.fit_predict(df)

  if len(np.unique(labels)) < len(df) and len(np.unique(labels)) > 1:
    media_silhueta = silhouette_score(df, labels)
    valores_silhueta.append(media_silhueta)
    quantil_plot.append(quantil)

valores_silhueta

[0.056194254181497635,
 0.11532411471942536,
 0.1588811972106386,
 0.18829779760106366,
 0.08106433788540647,
 0.07018083955012266,
 0.11424295614267553,
 0.10883641713826113,
 0.15058986290091397,
 0.21081904720122654,
 0.22092490313863042,
 0.220366867955623,
 0.2212837640957226,
 0.25582249060090395,
 0.25582249060090395,
 0.11942349194571159,
 0.26375348680377736]

In [54]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=faixa_quantil, y=valores_silhueta))
fig.update_layout(title="Valores de silhueta médios", xaxis_title="Quantil", yaxis_title="Valor médio de silhueta")
fig.show()

In [55]:
from sklearn.cluster import KMeans, MeanShift, DBSCAN, estimate_bandwidth
from sklearn.metrics import silhouette_score

In [56]:
agrupador_kmeans = KMeans(n_clusters=3)
agrupador_dbscan = DBSCAN(eps=2.1, min_samples=56, metric='manhattan')

bw = estimate_bandwidth(df, 0.28)
agrupador_meanshift = MeanShift(bandwidth=bw)

labels_kmeans = agrupador_kmeans.fit_predict(df)
labels_dbscan = agrupador_dbscan.fit_predict(df)
labels_meanshift = agrupador_meanshift.fit_predict(df)

In [57]:
labels_kmeans

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0, 2, 2, 2, 2,
       2, 2, 0, 2, 0, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2,
       2, 2, 2, 2, 0, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0], dtype=int32)

In [58]:
labels_dbscan

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0, -1, -1, -1,  0,  0,  0,  0,  0,  0,
        0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0, -1,  0, -1,  0,  0,  0,  0,  0, -1,
        0,  0, -1,  0,  0, -1,  0,  0,  0,  0,  0, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1])

In [59]:
labels_meanshift

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [60]:
coeficiente_kmeans = silhouette_score(df, labels_kmeans)
coeficiente_dbscan = silhouette_score(df, labels_dbscan)
coeficiente_meanshift = silhouette_score(df, labels_meanshift)

In [61]:
coeficiente_kmeans

0.3008938518500134

In [62]:
coeficiente_dbscan

0.2770638783298969

In [63]:
coeficiente_meanshift

0.26375348680377736

In [64]:
faixa_min_samples = [i for i in range(1,100,5)]
faixa_eps = [i/10 for i in range(1,100,1)]

In [66]:
agrupador.cluster_centers_

array([[0.51298762, 0.31322948, 0.53639509, 0.45897514, 0.32289003,
        0.44776876, 0.35300323, 0.4345172 , 0.37058824, 0.31514254,
        0.39017695, 0.49390218, 0.32896283]])

In [67]:
from collections import Counter

In [68]:
valores_silhueta = []
eps_plot = []
min_samples_plot = []
for min_samples in faixa_min_samples:
  for eps in faixa_eps:
    labels = 0
    agrupador = DBSCAN(eps = eps, min_samples = min_samples, metric = 'manhattan')
    agrupador.fit_predict(df)
    labels = agrupador.labels_
    if(Counter(labels)[0] < len(df) and Counter(labels)[0] > 1): #porque não é possível calcular
    # silhueta para apenas  um cluster ou para número de clústeres igual
    # ao número de dados 
      media_silhueta = silhouette_score(df, labels)
      valores_silhueta.append(media_silhueta)
      eps_plot.append(eps)
      min_samples_plot.append(min_samples)

In [69]:
ind = valores_silhueta.index(max(valores_silhueta))
#@title Default title text
fig = go.Figure()
fig.add_trace(go.Scatter3d(x=[min_samples_plot[ind]],
                         y = [eps_plot[ind]], z = [max(valores_silhueta)],
                         mode = 'markers',marker_line_color="midnightblue", 
                          marker_symbol=['x']))
fig.add_trace(go.Scatter3d(x=min_samples_plot,
                         y = eps_plot, z = valores_silhueta,
                         mode = 'markers',
                        text = labels))
fig.update_layout(scene = dict(
                    xaxis_title='eps',
                    yaxis_title='min_samples',
                    zaxis_title='silhueta'))
fig.show()

In [70]:
# pega o índice do vamior valor do coeficiente de silhueta
ind = valores_silhueta.index(max(valores_silhueta))
# printa os valores de eps e min_samples para o maior valor de coeficiente de silhueta encontrado
print(eps_plot[ind])
print(min_samples_plot[ind])

2.1
56


In [71]:
print(max(valores_silhueta))

0.2770638783298969
